Pae.Web/Pae.web/Pae.web/Controllers/InstitucionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Pae.web.Data;
using Pae.web.Data.Entities;
using Pae.web.Helpers;
using Pae.web.Models;

namespace Pae.web.Controllers
{
    public class InstitucionsController : Controller
    {
        private readonly DataContext _context;
        private readonly IConverterHelper _converterHelper;

        public InstitucionsController(
            DataContext context,
            IConverterHelper converterHelper)
        {
            _context = context;
          _converterHelper = converterHelper;
        }

        // GET: Institucions
        public async Task<IActionResult> Index()
        {
            return View(await _context.Institucions.ToListAsync());
        }

        // GET: Institucions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var institucion = await _context.Institucions
                .Include(a => a.Sedes)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (institucion == null)
            {
                return NotFound();
            }

            return View(institucion);
        }

        // GET: Institucions/Create
        public IActionResult Create()
        {

          
            return View();
        }

        // POST: Institucions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NameIntitucion")] Institucion institucion)
        {
            if (ModelState.IsValid)
            {
                _context.Add(institucion);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(institucion);
        }

        // GET: Institucions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var institucion = await _context.Institucions.FindAsync(id);
            if (institucion == null)
            {
                return NotFound();
            }
            return View(institucion);
        }

        // POST: Institucions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NameIntitucion")] Institucion institucion)
        {
            if (id != institucion.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(institucion);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InstitucionExists(institucion.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(institucion);
        }

       
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var institucion = await _context.Institucions
                .FirstOrDefaultAsync(m => m.Id == id);
            if (institucion == null)
            {
                return NotFound();
               
            }
            try
            {

                _context.Institucions.Remove(institucion);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {

                ViewBag.Message = $"Excepcion no Controlada: {e.Message} Detalle: {e.InnerException}";
                return RedirectToAction(nameof(Index));
            }
        }

        public async Task<IActionResult> DeleteSede(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sons = await _context.Sedes
                .Include(pi => pi.Institucion)
                .FirstOrDefaultAsync(pi => pi.Id == id.Value);
            if (sons == null)
            {
                return NotFound();
            }
            try
            {
                _context.Sedes.Remove(sons);
                await _context.SaveChangesAsync();
                return RedirectToAction($"{nameof(Details)}/{sons.Institucion.Id}");
            }
            catch (Exception e)
            {

                ViewBag.Message = $"Excepcion no Controlada: {e.Message} Detalle: {e.InnerException}";
                return View();
            }
           
        }

        private bool InstitucionExists(int id)
        {
            return _context.Institucions.Any(e => e.Id == id);
        }
        public async Task<IActionResult> AddSede(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var sede = await _context.Institucions.FindAsync(id);
            if (sede == null)
            {
                return NotFound();
            }
            var model = new AddSedeViewModel
            {
                InstitucionId=sede.Id
             
               
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> AddSede(AddSedeViewModel model)
        {
            if (ModelState.IsValid)
            {
                var modelfull = new AddSedeViewModel
                {
                    InstitucionId = model.Id,
                    NameSedes = model.NameSedes
                    
                };
                var sede = await _converterHelper.ToSedeAsync(modelfull, true);
                _context.Sedes.Add(sede);
                await _context.SaveChangesAsync();
                return RedirectToAction($"Details/{model.InstitucionId}");
            }
           
            return View(model);
        }
        public async Task<IActionResult> EditSede(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var exams = await _context.Sedes
                .Include(s => s.Institucion)
               
                .FirstOrDefaultAsync(s => s.Id == id);
            if (exams == null)
            {
                return NotFound();
            }

            return View(_converterHelper.ToSedeViewModel(exams));
        }
        [HttpPost]
        public async Task<IActionResult> EditSede(AddSedeViewModel model)
        {
            if (ModelState.IsValid)
            {
                var contract = await _converterHelper.ToSedeAsync(model, false);
                _context.Sedes.Update(contract);
                await _context.SaveChangesAsync();
                return RedirectToAction($"{nameof(Details)}/{model.InstitucionId}");
            }
            return View(model);

           
        }

    }
}

Pae.Web/Pae.web/Pae.web/Controllers/SincroController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Pae.web.Data;
using Pae.web.Data.Entities;
using Pae.web.Models;


namespace Pae.web.Controllers
{
    public class SincroController : Controller
    {
        SincroModel cn = new SincroModel();
        private readonly DataContext _context;


        public SincroController(DataContext context

            )
        {
            _context = context;

        }
        public async Task<IActionResult> Index()
        {

            return View(await _context.Sincros.ToListAsync());
        }

        //[HttpPost]
        //public async Task<IActionResult> Index(int? id)
        //{
        //    if (id == null)
        //    {
        //        ViewBag.Message = $"Seleccione un Documento de Excel";
        //    }
        //    try
        //    {

        //    }
        //    catch (Exception)
        //    {

        //        throw;
        //    }
        //}


            public async Task<IActionResult> GetStudentList(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var dateup = await _context.Sincros

                .FirstOrDefaultAsync(o => o.Id == id.Value);
            if (dateup == null)
            {
                return NotFound();
            }

            string fullUpdate = dateup.EndUpdate;

            try
            {

                var fileName = cn.StudentsServer(fullUpdate);
                if (fileName.Tables[0].Rows.Count > 0)
                {
                    int contadorSave = 0;
                    int contadorUpdate = 0;

                    var studentIds = _context.Estudents.Select(t => t.Document).ToList();

                    List<Estudents> newEstudents = new List<Estudents>();

                    foreach (DataRow dr in fileName.Tables[0].Rows)
                    {
                        string nOder = dr["NOrden"].ToString();
                        string doc = dr["Document"].ToString();
                        string fullName = dr["FullName"].ToString();
                        string acudienteName = dr["AcudienteName"].ToString();
                        string documentAcu = dr["DocumentAcu"].ToString();
                        string mesas = dr["Mesas"].ToString();
                        string jornada = dr["Jornada"].ToString();
                        string autDelivery = dr["AutDelivery"].ToString();
                        string sedes = dr["SedesId"].ToString();
                        string dateUpdate = dr["DateUpdate"].ToString();

                        bool exits = studentIds.Any(t => t == doc);

                        if (!exits)
                        {
                            Estudents newEstudent = new Estudents()
                            {
                                NOrden = nOder,
                                FullName = fullName,
                                Document = doc,
                                AcudienteName = acudienteName,
                                DocumentAcu = documentAcu,
                                
                                Sedes = await _context.Sedes.FindAsync(Convert.ToInt32(sedes)),
                                Mesas = mesas,
                                AutDelivery = autDelivery,
                                Jornada = jornada,
                                FechaActualización = Convert.ToDateTime(dateUpdate)

                            };

                            newEstudents.Add(newEstudent);

                            contadorSave++;
                        }
                        else
                        {
                            Estudents updatedEstudent = await _context.Estudents.SingleAsync(t => t.Document == doc);
                            if (Convert.ToDateTime(dateUpdate) > updatedEstudent.FechaActualización)
                            {
                                updatedEstudent.NOrden = $"{updatedEstudent.NOrden}, {nOder}";
                                updatedEstudent.Document = updatedEstudent.Document;
                                updatedEstudent.Sedes = await _context.Sedes.FindAsync(Convert.ToInt32(sedes));
                                updatedEstudent.FullName = updatedEstudent.FullName;
                                updatedEstudent.AcudienteName = updatedEstudent.AcudienteName;
                                updatedEstudent.DocumentAcu = updatedEstudent.DocumentAcu;
                                updatedEstudent.AutDelivery = $"{updatedEstudent.AutDelivery}, {autDelivery}";
                                updatedEstudent.Mesas = $"{updatedEstudent.Mesas}, {mesas}";
                                updatedEstudent.Jornada = updatedEstudent.Jornada;
                                updatedEstudent.FechaActualización = Convert.ToDateTime(dateUpdate);
                                contadorUpdate++;
                                _context.Estudents.Update(updatedEstudent);
                            }
                        }

                    }

                    if (newEstudents.Any())
                    {
                        _context.Estudents.AddRange(newEstudents);
                    }

                    await _context.SaveChangesAsync();

                    ViewBag.Message = $"Se Encontraron {fileName.Tables[0].Rows.Count} Registros de los cuales {contadorSave} son Nuevos y {contadorUpdate} se actualizaron.";


                }
                else
                {
                    ViewBag.Message = $"No hay Registros Nuevos";
                }
                return RedirectToAction($"Index");
            }
            catch (Exception e)
            {
                ViewBag.Message = $"Exeption: {e.Message}";
                return RedirectToAction($"Index");

            }



        }
        public async Task<IActionResult> GetInstitucionList(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var dateup = await _context.Sincros

                .FirstOrDefaultAsync(o => o.Id == id.Value);
            if (dateup == null)
            {
                return NotFound();
            }

            string fullUpdate = dateup.EndUpdate;

            try
            {

                var fileName = cn.InstitucionServer(fullUpdate);
                if (fileName.Tables[0].Rows.Count > 0)
                {
                    int contadorSave = 0;
                    int contadorUpdate = 0;
                    foreach (DataRow dr in fileName.Tables[0].Rows)
                    {

                        string fullName = dr["NameIntitucion"].ToString();
                        string ids = dr["Idins"].ToString();
                        string dateUpdate = dr["FechaActualización"].ToString();

                        var exits = await _context.Institucions
                                   .FirstOrDefaultAsync(s => s.IdIns == ids);

                        if (exits == null)
                        {
                            _context.Institucions.Add(new Institucion()
                            {
                                NameIntitucion = fullName,
                                IdIns=ids,
                                FechaActualización = Convert.ToDateTime(dateUpdate)

                            }); contadorSave++;
                            await _context.SaveChangesAsync();

                        }
                        else
                        {
                            if (Convert.ToDateTime(dateUpdate) > exits.FechaActualización)
                            {

                                exits.NameIntitucion = fullName;
                                exits.FechaActualización = Convert.ToDateTime(dateUpdate);
                                contadorUpdate++;
                                _context.Institucions.Update(exits);
                                await _context.SaveChangesAsync();
                            }


                        }

                    }
                   
                    return ViewBag.Success = $"Se Encontraron {fileName.Tables[0].Rows.Count} Registros de los cuales {contadorSave} son Nuevos y {contadorUpdate} se actualizaron.";


                }
                else
                {
                    ViewBag.Success = $"No hay Registros Nuevos";
                }
                return RedirectToAction($"Index");
            }
            catch (Exception e)
            {

                ViewBag.Message = $"Excepcion no Controlada: {e.Message} mas detalles:{e.InnerException}";
                return RedirectToAction($"Index");
            }



        }
        public async Task<IActionResult> GetSedesList(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var dateup = await _context.Sincros

                .FirstOrDefaultAsync(o => o.Id == id.Value);
            if (dateup == null)
            {
                return NotFound();
            }

            string fullUpdate = dateup.EndUpdate;

            try
            {

                var fileName = cn.SedesServer(fullUpdate);
                if (fileName.Tables[0].Rows.Count > 0)
                {
                    int contadorSave = 0;
                    int contadorUpdate = 0;
                    foreach (DataRow dr in fileName.Tables[0].Rows)
                    {

                        int ids = (int)dr["Id"];
                        string fullName = dr["NameSedes"].ToString();
                        string idSede = dr["IdSede"].ToString();
                        string dateUpdate = dr["FechaActualización"].ToString();
                        int idInstitucion = Convert.ToInt32(dr["InstitucionId"]);

Pae.Web/Pae.web/Pae.web/Views/Shared/_DeleteDialogModal.cshtml
<div class="modal fade" id="deleteDialog" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete Item</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Do you want to delete the record?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-danger" id="btnYesDelete">Delete</button>
            </div>
        </div>
    </div>
</div>

Pae.Web/Pae.web/Pae.web/Views/Shared/_Exception.cshtml
<div class="text-success">
<p>
    @ViewBag.Success
</p>
</div>
<div class="text-success">
    <p>
        @ViewBag.Message
    </p>
</div>

Pae.Web/Pae.web/Pae.web/Views/Shared/_Exepction.cshtml
<div class="text-success">
<p>
    @ViewBag.Success
</p>
</div>

Pae.Web/Pae.web/Pae.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pae.web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Pae.web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                   
                    <li><a asp-area="" asp-controller="UploadStudent" asp-action="Index">Subir Data</a></li>
                    <li><a asp-area="" asp-controller="Sincro" asp-action="Index">Sincro</a></li>
                    <li><a asp-area="" asp-controller="ActaSequences" asp-action="Index">Config</a></li>
                    <li><a asp-area="" asp-controller="Institucions" asp-action="Index">Instituciones</a></li>
                    <li><a asp-area="" asp-controller="Estudents" asp-action="Index">Estudiantes</a></li>
                 
                </ul>
            </div>
        </div>
    </nav>


    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - Pae.web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>